# Generated by Django 5.2.5 on 2025-08-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='is_active',
        ),
    ]
