# Generated by Django 5.2.5 on 2025-08-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovacollabapp', '0002_enrollment_room_payment_enrollment_room_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admin_image',
            field=models.ImageField(null=True, upload_to='admin_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(null=True, upload_to='room_images/'),
        ),
    ]
