# Generated by Django 5.2.5 on 2025-08-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovacollabapp', '0004_chatsession_chatsummary'),
    ]

    operations = [
    ]
