# Generated by Django 5.2.5 on 2025-08-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovacollabapp', '0005_auto_20250815_1447'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('user', 'room')},
        ),
    ]
