# Generated by Django 5.2.5 on 2025-08-15 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovacollabapp', '0006_alter_chatsession_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('material_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video'), ('image', 'Image'), ('text', 'Text Document'), ('link', 'External Link'), ('other', 'Other')], default='other', max_length=20)),
                ('access_level', models.CharField(choices=[('free', 'Free Access'), ('premium', 'Premium Only')], default='free', max_length=20)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('external_link', models.URLField(blank=True, help_text='For external resources', null=True)),
                ('content', models.TextField(blank=True, help_text='Text content for text-based materials')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Number of pages for documents', null=True)),
                ('duration', models.CharField(blank=True, help_text='Duration for videos/audio', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_materials', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='innovacollabapp.room')),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['room', 'access_level'], name='innovacolla_room_id_b6b41e_idx'), models.Index(fields=['author'], name='innovacolla_author__57be8b_idx')],
            },
        ),
    ]
