# Generated by Django 5.2.5 on 2025-08-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovacollabapp', '0007_studymaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='admin_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
