# Generated by Django 5.2.5 on 2025-08-15 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_subject_pdf_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='course.subject'),
        ),
    ]
